# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"VoxelData": "00_preprocess.ipynb",
         "log_datadir_as_artifact": "00_utils.ipynb"}

modules = ["preprocess.py",
           "utils.py"]

doc_url = "https://ayulockin.github.io/kagglerecipes/"

git_url = "https://github.com/ayulockin/kagglerecipes/tree/main/"

def custom_doc_links(name): return None
