# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TINY_DATA_PATH": "00_data.ipynb",
         "VoxelData": "01_preprocess.ipynb",
         "globtastic": "02_utils.ipynb",
         "compile_re": "02_utils.ipynb",
         "walk": "02_utils.ipynb",
         "kaggle_braintumor_meta_cols": "02_utils.ipynb",
         "get_dicom_metadata": "02_utils.ipynb",
         "get_patient_id": "02_utils.ipynb",
         "get_patient_BraTS21ID_path": "02_utils.ipynb",
         "get_all_dicom_metadata": "02_utils.ipynb",
         "get_image_plane": "02_utils.ipynb",
         "log_df_as_tables": "03_wandb_utils.ipynb",
         "log_to_artifacts": "03_wandb_utils.ipynb",
         "plot_basic_charts": "04_wandb_viz.ipynb"}

modules = ["data.py",
           "preprocess.py",
           "utils.py",
           "wandb_utils.py",
           "wandb_viz.py"]

doc_url = "https://ayulockin.github.io/kagglerecipes/"

git_url = "https://github.com/ayulockin/kagglerecipes/tree/main/"

def custom_doc_links(name): return None
