# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"VoxelData": "01_preprocess.ipynb",
         "kaggle_braintumor_meta_cols": "02_utils.ipynb",
         "get_dicom_metadata": "02_utils.ipynb",
         "get_all_dicom_metadata": "02_utils.ipynb",
         "get_patient_id": "02_utils.ipynb",
         "get_image_plane": "02_utils.ipynb",
         "log_datadir_as_artifact": "03_wandb_utils.ipynb"}

modules = ["preprocess.py",
           "utils.py",
           "wandb_utils.py"]

doc_url = "https://ayulockin.github.io/kagglerecipes/"

git_url = "https://github.com/ayulockin/kagglerecipes/tree/main/"

def custom_doc_links(name): return None
