# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_wandb_utils.ipynb (unless otherwise specified).

__all__ = ['log_datadir_as_artifact']

# Cell
import os
import wandb

# Cell
def log_datadir_as_artifact(wandb_run, path_to_dir, artifact_name, artifact_type='dataset'):
    """
    Logs a data directory as an artifact in wandb.
    wandb_run: wandb.Run object
    path_to_dir: path to the data directory
    artifact_name: name of the artifact
    artifact_type: type of the artifact
    """

    artifact = wandb.Artifact(artifact_name, type=artifact_type)
    artifact.add_dir(path_to_dir)
    wandb_run.log_artifact(artifact)